package program.view.responses;

public enum LoginMenuResponses {
    PASSWORDS_DIDNT_MATCH,
    PASSWORD_AND_USERNAME_DIDNT_MATCH,
    USER_LOGIN_SUCCESSFUL,
    USER_CREATED_SUCCESSFULLY,
    USER_WITH_THIS_NICKNAME_EXITS,
    USER_WITH_THIS_USERNAME_EXITS, PLEASE_FILL_ALL_OF_THE_FIELDS,
}
