package program.view.responses;

public enum ProfileMenuResponses {
    PLEASE_ENTER_A_NEW_PASSWORD,
    CURRENT_PASSWORD_IS_INVALID,
    NICKNAME_CHANGED_SUCCESSFULLY,
    USER_WITH_NICKNAME_ALREADY_EXISTS,
    PASSWORD_CHANGED_SUCCESSFULLY, INVALID_PASSWORD,
}
